# Base configs
baseurl: "http://polyrhythm.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "images by ryan jones"
subtitle: ""
author: "ryan jones"
bio: "Analog enthusiast."
publicise: ""
web_design: ""
social_urls:
  facebook: "https://www.facebook.com/polyrhytmical"
  twitter: "https://www.twitter.com/poly_rhythm"
  instagram: "https://www.instagram.com/polyrhytmical"
  dribbble: ""
  linkedin: ""
  github: "https://www.github.com/Polyrhythm"
